apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{pg.svc_name}}"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "{{pg.storage_size}}"
  hostPath:
    path: /mnt/postgres/data
  accessModes:
    - ReadWriteOnce
